FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /workspace
COPY commercecore/pom.xml ./pom.xml
COPY commercecore/.mvn ./.mvn
COPY commercecore/mvnw ./mvnw
COPY commercecore/src ./src
RUN chmod +x mvnw && ./mvnw -q -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /workspace/target/*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
